FROM node:22-alpine AS build
WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .

ARG PUBLIC_GOOGLE_SHEETS_ID
ARG PUBLIC_GOOGLE_API_KEY
ARG PUBLIC_GOOGLE_SHEET_NAME
ARG PUBLIC_GOOGLE_SHEET_RANGE
ARG PUBLIC_POLLING_INTERVAL
ARG PUBLIC_SITE_URL

ENV PUBLIC_GOOGLE_SHEETS_ID=$PUBLIC_GOOGLE_SHEETS_ID
ENV PUBLIC_GOOGLE_API_KEY=$PUBLIC_GOOGLE_API_KEY
ENV PUBLIC_GOOGLE_SHEET_NAME=$PUBLIC_GOOGLE_SHEET_NAME
ENV PUBLIC_GOOGLE_SHEET_RANGE=$PUBLIC_GOOGLE_SHEET_RANGE
ENV PUBLIC_POLLING_INTERVAL=$PUBLIC_POLLING_INTERVAL
ENV PUBLIC_SITE_URL=$PUBLIC_SITE_URL

RUN npm run build

FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
